# Generated by Django 3.2.3 on 2021-06-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='borad',
            new_name='board',
        ),
    ]
